# Generated by Django 4.2.2 on 2024-01-10 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delicrave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='catalogitem',
            name='dessert',
        ),
        migrations.RemoveField(
            model_name='catalogitem',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='catalogitem',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='order',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AddField(
            model_name='dessert',
            name='flavor',
            field=models.ForeignKey(db_column='Flavor', null=True, on_delete=django.db.models.deletion.CASCADE, to='delicrave.flavor'),
        ),
        migrations.AddField(
            model_name='dessert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dessert_images/'),
        ),
        migrations.AddField(
            model_name='dessert',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dessert',
            name='unit',
            field=models.CharField(blank=True, db_column='Unit', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_column='Name', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(db_column='Name', max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(db_column='Password', max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(db_column='UserName', max_length=15),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='name',
            field=models.CharField(db_column='Name', max_length=20),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='name',
            field=models.CharField(db_column='Name', max_length=20),
        ),
        migrations.RemoveField(
            model_name='flavorcat',
            name='category',
        ),
        migrations.RemoveField(
            model_name='flavorcat',
            name='flavor',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=10, null=True),
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CatalogItem',
        ),
        migrations.DeleteModel(
            name='OrderHistory',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='dessert',
            field=models.ForeignKey(blank=True, db_column='dessert', null=True, on_delete=django.db.models.deletion.CASCADE, to='delicrave.dessert'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(db_column='Order', on_delete=django.db.models.deletion.CASCADE, to='delicrave.order'),
        ),
        migrations.AddField(
            model_name='customercart',
            name='customer',
            field=models.OneToOneField(db_column='Customer', on_delete=django.db.models.deletion.CASCADE, to='delicrave.customer'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(blank=True, db_column='CustomerCart', null=True, on_delete=django.db.models.deletion.CASCADE, to='delicrave.customercart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='dessert',
            field=models.ForeignKey(blank=True, db_column='Dessert', null=True, on_delete=django.db.models.deletion.CASCADE, to='delicrave.dessert'),
        ),
        migrations.AddField(
            model_name='flavorcat',
            name='category',
            field=models.ForeignKey(blank=True, db_column='Category', null=True, on_delete=django.db.models.deletion.CASCADE, to='delicrave.category'),
        ),
        migrations.AddField(
            model_name='flavorcat',
            name='flavor',
            field=models.ForeignKey(blank=True, db_column='Flavor', null=True, on_delete=django.db.models.deletion.CASCADE, to='delicrave.flavor'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='customer',
            field=models.OneToOneField(blank=True, db_column='Customer', null=True, on_delete=django.db.models.deletion.CASCADE, to='delicrave.customer'),
        ),
    ]
