# Generated by Django 4.2.2 on 2023-12-30 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delicrave', '0002_remove_cart_catalogitem_cart_catalogitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(db_column='Customer', on_delete=django.db.models.deletion.CASCADE, to='delicrave.customer')),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(blank=True, db_column='Customer', null=True, on_delete=django.db.models.deletion.CASCADE, to='delicrave.customercart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='catalogitem',
            field=models.ManyToManyField(db_column='CatalogItem', to='delicrave.catalogitem'),
        ),
    ]
