# Generated by Django 4.2.2 on 2023-12-30 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delicrave', '0003_cartitem_customercart_delete_cart_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(blank=True, db_column='CustomerCart', null=True, on_delete=django.db.models.deletion.CASCADE, to='delicrave.customercart'),
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='catalogitem',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='catalogitem',
            field=models.ForeignKey(blank=True, db_column='CatalogItem', null=True, on_delete=django.db.models.deletion.CASCADE, to='delicrave.catalogitem'),
        ),
    ]
