# Generated by Django 4.2.2 on 2023-12-30 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delicrave', '0004_alter_cartitem_cart_remove_cartitem_catalogitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('catalogitem', models.ForeignKey(blank=True, db_column='CatalogItem', null=True, on_delete=django.db.models.deletion.CASCADE, to='delicrave.catalogitem')),
                ('order', models.ForeignKey(db_column='Order', on_delete=django.db.models.deletion.CASCADE, to='delicrave.order')),
            ],
        ),
        migrations.AddField(
            model_name='dessert',
            name='flavor',
            field=models.ForeignKey(db_column='Flavor', null=True, on_delete=django.db.models.deletion.CASCADE, to='delicrave.flavor'),
        ),
        migrations.DeleteModel(
            name='OrderHistory',
        ),
    ]
