# Generated by Django 4.2.2 on 2023-12-30 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delicrave', '0005_orderitem_dessert_flavor_delete_orderhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogitem',
            name='dessert',
        ),
        migrations.RemoveField(
            model_name='catalogitem',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='flavorcat',
            name='category',
        ),
        migrations.RemoveField(
            model_name='flavorcat',
            name='flavor',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='customer',
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='dessert',
            field=models.ForeignKey(blank=True, db_column='Dessert', null=True, on_delete=django.db.models.deletion.CASCADE, to='delicrave.dessert'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='unit',
            field=models.ForeignKey(blank=True, db_column='Unit', null=True, on_delete=django.db.models.deletion.CASCADE, to='delicrave.unit'),
        ),
        migrations.AddField(
            model_name='flavorcat',
            name='category',
            field=models.ForeignKey(blank=True, db_column='Category', null=True, on_delete=django.db.models.deletion.CASCADE, to='delicrave.category'),
        ),
        migrations.AddField(
            model_name='flavorcat',
            name='flavor',
            field=models.ForeignKey(blank=True, db_column='Flavor', null=True, on_delete=django.db.models.deletion.CASCADE, to='delicrave.flavor'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='customer',
            field=models.OneToOneField(blank=True, db_column='Customer', null=True, on_delete=django.db.models.deletion.CASCADE, to='delicrave.customer'),
        ),
    ]
