# Generated by Django 4.2.2 on 2024-01-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delicrave', '0006_remove_catalogitem_dessert_remove_catalogitem_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_column='Name', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(db_column='Name', max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(db_column='Password', max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(db_column='UserName', max_length=15),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='name',
            field=models.CharField(db_column='Name', max_length=20),
        ),
        migrations.AlterField(
            model_name='flavor',
            name='name',
            field=models.CharField(db_column='Name', max_length=20),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(blank=True, db_column='Name', max_length=20),
        ),
    ]
