# Generated by Django 4.2.2 on 2024-01-05 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delicrave', '0007_alter_category_name_alter_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='catalogitem',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='catalogitem',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='dessert',
            field=models.ForeignKey(blank=True, db_column='Dessert', null=True, on_delete=django.db.models.deletion.CASCADE, to='delicrave.dessert'),
        ),
        migrations.AddField(
            model_name='dessert',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dessert',
            name='unit',
            field=models.CharField(blank=True, db_column='Unit', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='dessert',
            field=models.ForeignKey(blank=True, db_column='dessert', null=True, on_delete=django.db.models.deletion.CASCADE, to='delicrave.dessert'),
        ),
        migrations.DeleteModel(
            name='CatalogItem',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
