# Generated by Django 4.2.2 on 2024-01-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delicrave', '0008_remove_cartitem_catalogitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AddField(
            model_name='dessert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dessert_images/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel')], default='Pending', max_length=10, null=True),
        ),
    ]
